#!/usr/bin/env python
"""Write an equivalent function to the build in filter() function that takes
a function and a single list and returns a new list of elements where the
function evaluates to true.
Call your function _filter().
For example: _filter(lambda x: x > 0, [1,-2, 3,-4])
(the lambda returns True if x is positive) returns:
[1, 3]
Write an equivalent function to the build in map() function that takes
a function and a single sequence and returns a new list of elements where the
function has been applied to each element of the sequence.
Call your function _map().
For example: _map(lambda x: x.upper(), 'abcdef')
returns:
['A', 'B', 'C', 'D', 'E', 'F']
